// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package gensqlite

import (
	"context"
)

const clearAccountTokens = `-- name: ClearAccountTokens :exec
UPDATE connected_accounts
   SET access_token_enc  = ?2,
       refresh_token_enc = NULL,
       token_expires_at  = NULL,
       updated_at        = ?3
 WHERE id = ?1
`

type ClearAccountTokensParams struct {
	ID             string
	AccessTokenEnc []byte
	UpdatedAt      string
}

// ClearAccountTokens wipes stored credentials without touching the row, so a
// disconnected account stops being usable while its id -- and therefore every
// file_shards.connected_account_id pointing at it -- survives. The Postgres
// version casts an empty string to bytea; here the caller passes an empty
// blob, since access_token_enc is NOT NULL.
func (q *Queries) ClearAccountTokens(ctx context.Context, arg ClearAccountTokensParams) error {
	_, err := q.db.ExecContext(ctx, clearAccountTokens, arg.ID, arg.AccessTokenEnc, arg.UpdatedAt)
	return err
}

const consumeOAuthState = `-- name: ConsumeOAuthState :one
DELETE FROM oauth_states
 WHERE state_hash = ?1
   AND expires_at > ?2
RETURNING state_hash, user_id, kind, redirect_to, pkce_verifier, created_at, expires_at
`

type ConsumeOAuthStateParams struct {
	StateHash []byte
	ExpiresAt string
}

// ConsumeOAuthState is single use by construction: the row is deleted as it is
// read, so a replayed callback finds nothing. The expiry predicate is in SQL so
// a stale state cannot be accepted by a clock-skewed application check.
func (q *Queries) ConsumeOAuthState(ctx context.Context, arg ConsumeOAuthStateParams) (OauthState, error) {
	row := q.db.QueryRowContext(ctx, consumeOAuthState, arg.StateHash, arg.ExpiresAt)
	var i OauthState
	err := row.Scan(
		&i.StateHash,
		&i.UserID,
		&i.Kind,
		&i.RedirectTo,
		&i.PkceVerifier,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createConnectedAccount = `-- name: CreateConnectedAccount :one

INSERT INTO connected_accounts (
    id, user_id, kind, provider_account_id, email, display_name,
    access_token_enc, refresh_token_enc, token_expires_at, ordinal,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, kind, provider_account_id, email, display_name, access_token_enc, refresh_token_enc, token_expires_at, status, last_error, ordinal, app_folder_id, created_at, updated_at
`

type CreateConnectedAccountParams struct {
	ID                string
	UserID            string
	Kind              string
	ProviderAccountID string
	Email             string
	DisplayName       string
	AccessTokenEnc    []byte
	RefreshTokenEnc   []byte
	TokenExpiresAt    *string
	Ordinal           int64
	CreatedAt         string
	UpdatedAt         string
}

// SQLite dialect of internal/db/queries/accounts.sql. Same contracts; the
// differences are noted where they exist. now() becomes a bound parameter
// throughout, as in sessions.sql.
//
// KEEP THIS FILE ASCII-ONLY -- see the note at the top of sessions.sql. sqlc
// v1.31.1 miscounts multi-byte characters in comments and truncates the query
// that follows.
func (q *Queries) CreateConnectedAccount(ctx context.Context, arg CreateConnectedAccountParams) (ConnectedAccount, error) {
	row := q.db.QueryRowContext(ctx, createConnectedAccount,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.ProviderAccountID,
		arg.Email,
		arg.DisplayName,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.TokenExpiresAt,
		arg.Ordinal,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ConnectedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ProviderAccountID,
		&i.Email,
		&i.DisplayName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.Status,
		&i.LastError,
		&i.Ordinal,
		&i.AppFolderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOAuthState = `-- name: CreateOAuthState :exec
INSERT INTO oauth_states (state_hash, user_id, kind, redirect_to, pkce_verifier, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateOAuthStateParams struct {
	StateHash    []byte
	UserID       string
	Kind         string
	RedirectTo   string
	PkceVerifier *string
	CreatedAt    string
	ExpiresAt    string
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthState,
		arg.StateHash,
		arg.UserID,
		arg.Kind,
		arg.RedirectTo,
		arg.PkceVerifier,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteConnectedAccount = `-- name: DeleteConnectedAccount :execrows
DELETE FROM connected_accounts WHERE id = ? AND user_id = ?
`

type DeleteConnectedAccountParams struct {
	ID     string
	UserID string
}

// DeleteConnectedAccount is deliberately NOT used to disconnect a drive: the
// ON DELETE SET NULL on file_shards.connected_account_id would orphan every
// shard the drive held, unrecoverably (known issue #19). Disconnect soft
// deletes via SetAccountStatus + ClearAccountTokens instead. This remains for
// true row removal, e.g. hard-deleting a user's data.
func (q *Queries) DeleteConnectedAccount(ctx context.Context, arg DeleteConnectedAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConnectedAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :execrows
DELETE FROM oauth_states WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOAuthStates, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAppFolderID = `-- name: GetAppFolderID :one
SELECT app_folder_id FROM connected_accounts WHERE id = ?
`

func (q *Queries) GetAppFolderID(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRowContext(ctx, getAppFolderID, id)
	var app_folder_id *string
	err := row.Scan(&app_folder_id)
	return app_folder_id, err
}

const getConnectedAccount = `-- name: GetConnectedAccount :one
SELECT id, user_id, kind, provider_account_id, email, display_name, access_token_enc, refresh_token_enc, token_expires_at, status, last_error, ordinal, app_folder_id, created_at, updated_at FROM connected_accounts WHERE id = ? AND user_id = ?
`

type GetConnectedAccountParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetConnectedAccount(ctx context.Context, arg GetConnectedAccountParams) (ConnectedAccount, error) {
	row := q.db.QueryRowContext(ctx, getConnectedAccount, arg.ID, arg.UserID)
	var i ConnectedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ProviderAccountID,
		&i.Email,
		&i.DisplayName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.Status,
		&i.LastError,
		&i.Ordinal,
		&i.AppFolderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectedAccountByProviderID = `-- name: GetConnectedAccountByProviderID :one
SELECT id, user_id, kind, provider_account_id, email, display_name, access_token_enc, refresh_token_enc, token_expires_at, status, last_error, ordinal, app_folder_id, created_at, updated_at FROM connected_accounts
 WHERE user_id = ? AND kind = ? AND provider_account_id = ?
`

type GetConnectedAccountByProviderIDParams struct {
	UserID            string
	Kind              string
	ProviderAccountID string
}

func (q *Queries) GetConnectedAccountByProviderID(ctx context.Context, arg GetConnectedAccountByProviderIDParams) (ConnectedAccount, error) {
	row := q.db.QueryRowContext(ctx, getConnectedAccountByProviderID, arg.UserID, arg.Kind, arg.ProviderAccountID)
	var i ConnectedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ProviderAccountID,
		&i.Email,
		&i.DisplayName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.Status,
		&i.LastError,
		&i.Ordinal,
		&i.AppFolderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAccountsForSync = `-- name: ListActiveAccountsForSync :many
SELECT id, user_id, kind, provider_account_id, email, display_name, access_token_enc, refresh_token_enc, token_expires_at, status, last_error, ordinal, app_folder_id, created_at, updated_at FROM connected_accounts
 WHERE status = 'active'
 ORDER BY created_at
`

// ListActiveAccountsForSync feeds the background quota ticker, which is not
// acting on behalf of a request and so has no user to scope by.
func (q *Queries) ListActiveAccountsForSync(ctx context.Context) ([]ConnectedAccount, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAccountsForSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close() //nolint:errcheck
	items := []ConnectedAccount{}
	for rows.Next() {
		var i ConnectedAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.ProviderAccountID,
			&i.Email,
			&i.DisplayName,
			&i.AccessTokenEnc,
			&i.RefreshTokenEnc,
			&i.TokenExpiresAt,
			&i.Status,
			&i.LastError,
			&i.Ordinal,
			&i.AppFolderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectedAccounts = `-- name: ListConnectedAccounts :many
SELECT id, user_id, kind, provider_account_id, email, display_name, access_token_enc, refresh_token_enc, token_expires_at, status, last_error, ordinal, app_folder_id, created_at, updated_at FROM connected_accounts
 WHERE user_id = ?
 ORDER BY ordinal, created_at
`

func (q *Queries) ListConnectedAccounts(ctx context.Context, userID string) ([]ConnectedAccount, error) {
	rows, err := q.db.QueryContext(ctx, listConnectedAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close() //nolint:errcheck
	items := []ConnectedAccount{}
	for rows.Next() {
		var i ConnectedAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.ProviderAccountID,
			&i.Email,
			&i.DisplayName,
			&i.AccessTokenEnc,
			&i.RefreshTokenEnc,
			&i.TokenExpiresAt,
			&i.Status,
			&i.LastError,
			&i.Ordinal,
			&i.AppFolderID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageAccounts = `-- name: ListStorageAccounts :many
SELECT ca.id,
       ca.kind,
       ca.email,
       ca.display_name,
       ca.status,
       ca.ordinal,
       ca.last_error,
       COALESCE(sa.total_bytes, 0) AS total_bytes,
       COALESCE(sa.used_bytes, 0) AS used_bytes,
       COALESCE(sa.reserved_bytes, 0) AS reserved_bytes,
       sa.last_synced_at
  FROM connected_accounts ca
  LEFT JOIN storage_accounts sa ON sa.connected_account_id = ca.id
 WHERE ca.user_id = ?
 ORDER BY ca.ordinal, ca.created_at
`

type ListStorageAccountsRow struct {
	ID            string
	Kind          string
	Email         string
	DisplayName   string
	Status        string
	Ordinal       int64
	LastError     string
	TotalBytes    int64
	UsedBytes     int64
	ReservedBytes int64
	LastSyncedAt  *string
}

// ListStorageAccounts returns capacity joined to the owning account. It is one
// query rather than a list plus a lookup per row, per Rules.md section 2.12.
func (q *Queries) ListStorageAccounts(ctx context.Context, userID string) ([]ListStorageAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStorageAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close() //nolint:errcheck
	items := []ListStorageAccountsRow{}
	for rows.Next() {
		var i ListStorageAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.Ordinal,
			&i.LastError,
			&i.TotalBytes,
			&i.UsedBytes,
			&i.ReservedBytes,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAccountOrdinal = `-- name: NextAccountOrdinal :one
SELECT COALESCE(MAX(ordinal), 0) + 1 FROM connected_accounts WHERE user_id = ?
`

func (q *Queries) NextAccountOrdinal(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextAccountOrdinal, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pendingStateCount = `-- name: PendingStateCount :one

SELECT COUNT(*) FROM oauth_states
`

// --- test support ---------------------------------------------------------
// Back the inspection helpers the accounts test suite uses (memstore.go has
// in-memory equivalents). Read-only apart from SetReservedBytes, and no
// production caller.
func (q *Queries) PendingStateCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, pendingStateCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pendingVerifiers = `-- name: PendingVerifiers :many
SELECT COALESCE(pkce_verifier, '') FROM oauth_states
`

func (q *Queries) PendingVerifiers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, pendingVerifiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close() //nolint:errcheck
	items := []string{}
	for rows.Next() {
		var pkce_verifier string
		if err := rows.Scan(&pkce_verifier); err != nil {
			return nil, err
		}
		items = append(items, pkce_verifier)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountStatus = `-- name: SetAccountStatus :exec
UPDATE connected_accounts
   SET status     = ?2,
       last_error = ?3,
       updated_at = ?4
 WHERE id = ?1
`

type SetAccountStatusParams struct {
	ID        string
	Status    string
	LastError string
	UpdatedAt string
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAccountStatus,
		arg.ID,
		arg.Status,
		arg.LastError,
		arg.UpdatedAt,
	)
	return err
}

const setAppFolderID = `-- name: SetAppFolderID :one
UPDATE connected_accounts
   SET app_folder_id = ?2,
       updated_at    = ?3
 WHERE id = ?1
   AND app_folder_id IS NULL
RETURNING app_folder_id
`

type SetAppFolderIDParams struct {
	ID          string
	AppFolderID *string
	UpdatedAt   string
}

// SetAppFolderID records where this account's shards live at the provider.
//
// The app_folder_id IS NULL predicate makes the write single-shot: if another
// process established a folder first, this one returns no row and the caller
// re-reads rather than overwriting a good id with a duplicate folder.
func (q *Queries) SetAppFolderID(ctx context.Context, arg SetAppFolderIDParams) (*string, error) {
	row := q.db.QueryRowContext(ctx, setAppFolderID, arg.ID, arg.AppFolderID, arg.UpdatedAt)
	var app_folder_id *string
	err := row.Scan(&app_folder_id)
	return app_folder_id, err
}

const setReservedBytes = `-- name: SetReservedBytes :exec
INSERT INTO storage_accounts (connected_account_id, reserved_bytes)
VALUES (?1, ?2)
ON CONFLICT (connected_account_id) DO UPDATE
   SET reserved_bytes = excluded.reserved_bytes
`

type SetReservedBytesParams struct {
	ConnectedAccountID string
	ReservedBytes      int64
}

func (q *Queries) SetReservedBytes(ctx context.Context, arg SetReservedBytesParams) error {
	_, err := q.db.ExecContext(ctx, setReservedBytes, arg.ConnectedAccountID, arg.ReservedBytes)
	return err
}

const setStorageAccountError = `-- name: SetStorageAccountError :exec
INSERT INTO storage_accounts (connected_account_id, last_error)
VALUES (?1, ?2)
ON CONFLICT (connected_account_id) DO UPDATE
   SET last_error = excluded.last_error
`

type SetStorageAccountErrorParams struct {
	ConnectedAccountID string
	LastError          string
}

func (q *Queries) SetStorageAccountError(ctx context.Context, arg SetStorageAccountErrorParams) error {
	_, err := q.db.ExecContext(ctx, setStorageAccountError, arg.ConnectedAccountID, arg.LastError)
	return err
}

const stateHashExists = `-- name: StateHashExists :one
SELECT COUNT(*) FROM oauth_states WHERE state_hash = ?
`

func (q *Queries) StateHashExists(ctx context.Context, stateHash []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, stateHashExists, stateHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateAccountTokens = `-- name: UpdateAccountTokens :one
UPDATE connected_accounts
   SET access_token_enc  = ?3,
       refresh_token_enc = COALESCE(?4, refresh_token_enc),
       token_expires_at  = ?5,
       email             = ?6,
       display_name      = ?7,
       status            = 'active',
       last_error        = '',
       updated_at        = ?8
 WHERE id = ?1
   AND user_id = ?2
RETURNING id, user_id, kind, provider_account_id, email, display_name, access_token_enc, refresh_token_enc, token_expires_at, status, last_error, ordinal, app_folder_id, created_at, updated_at
`

type UpdateAccountTokensParams struct {
	ID              string
	UserID          string
	AccessTokenEnc  []byte
	RefreshTokenEnc []byte
	TokenExpiresAt  *string
	Email           string
	DisplayName     string
	UpdatedAt       string
}

// UpdateAccountTokens refreshes the stored credentials for an account that is
// already linked. The user_id predicate is not decoration: it is what stops a
// callback from writing tokens into somebody else's row.
//
// Setting status back to 'active' is what makes reconnecting a disconnected
// drive work: Disconnect soft deletes by setting status = 'disabled' and
// clearing the tokens (issue #19), and this is the write that undoes both
// while keeping the row id -- and therefore every shard's link to it -- intact.
func (q *Queries) UpdateAccountTokens(ctx context.Context, arg UpdateAccountTokensParams) (ConnectedAccount, error) {
	row := q.db.QueryRowContext(ctx, updateAccountTokens,
		arg.ID,
		arg.UserID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.TokenExpiresAt,
		arg.Email,
		arg.DisplayName,
		arg.UpdatedAt,
	)
	var i ConnectedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ProviderAccountID,
		&i.Email,
		&i.DisplayName,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.Status,
		&i.LastError,
		&i.Ordinal,
		&i.AppFolderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStorageAccount = `-- name: UpsertStorageAccount :exec
INSERT INTO storage_accounts (connected_account_id, total_bytes, used_bytes, last_synced_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (connected_account_id) DO UPDATE
   SET total_bytes    = excluded.total_bytes,
       used_bytes     = excluded.used_bytes,
       last_synced_at = excluded.last_synced_at,
       last_error     = ''
`

type UpsertStorageAccountParams struct {
	ConnectedAccountID string
	TotalBytes         int64
	UsedBytes          int64
	LastSyncedAt       *string
}

func (q *Queries) UpsertStorageAccount(ctx context.Context, arg UpsertStorageAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertStorageAccount,
		arg.ConnectedAccountID,
		arg.TotalBytes,
		arg.UsedBytes,
		arg.LastSyncedAt,
	)
	return err
}
