// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gensqlite

type ConnectedAccount struct {
	ID                string
	UserID            string
	Kind              string
	ProviderAccountID string
	Email             string
	DisplayName       string
	AccessTokenEnc    []byte
	RefreshTokenEnc   []byte
	TokenExpiresAt    *string
	Status            string
	LastError         string
	Ordinal           int64
	AppFolderID       *string
	CreatedAt         string
	UpdatedAt         string
}

type File struct {
	ID            string
	UserID        string
	FolderID      *string
	Name          string
	SizeBytes     int64
	DeclaredMime  string
	ContentSha256 []byte
	IsStriped     int64
	IsEncrypted   int64
	Status        string
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     *string
	ReconciledAt  *string
}

type FileShard struct {
	ID                 string
	FileID             string
	Idx                int64
	ConnectedAccountID *string
	ProviderObjectID   string
	SizeBytes          int64
	PlainSizeBytes     int64
	PlainOffset        int64
	Sha256             []byte
	CreatedAt          string
}

type Folder struct {
	ID        string
	UserID    string
	ParentID  *string
	Name      string
	CreatedAt string
	UpdatedAt string
	DeletedAt *string
}

type InstanceMetadatum struct {
	ID        int64
	KeyID     string
	CreatedAt string
}

type OauthState struct {
	StateHash    []byte
	UserID       string
	Kind         string
	RedirectTo   string
	PkceVerifier *string
	CreatedAt    string
	ExpiresAt    string
}

type QuotaReservation struct {
	ID               string
	StorageAccountID string
	Bytes            int64
	UploadID         string
	CreatedAt        string
	ExpiresAt        string
}

type SecurityEvent struct {
	ID        int64
	UserID    *string
	Kind      string
	Detail    string
	Ip        *string
	UserAgent string
	CreatedAt string
}

type Session struct {
	ID          string
	UserID      string
	FamilyID    string
	PrevID      *string
	RefreshHash []byte
	UserAgent   string
	Ip          *string
	CreatedAt   string
	ExpiresAt   string
	UsedAt      *string
	RevokedAt   *string
	Epoch       int64
}

type StorageAccount struct {
	ConnectedAccountID string
	TotalBytes         int64
	UsedBytes          int64
	ReservedBytes      int64
	LastSyncedAt       *string
	LastError          string
}

type TokenFamily struct {
	ID        string
	UserID    string
	CreatedAt string
	RevokedAt *string
}

type Upload struct {
	ID            string
	UserID        string
	FileID        *string
	Status        string
	SizeBytes     int64
	BytesReceived int64
	Plan          string
	CreatedAt     string
	UpdatedAt     string
	ExpiresAt     string
}

type User struct {
	ID              string
	Email           string
	PasswordHash    string
	EmailVerifiedAt *string
	CreatedAt       string
	UpdatedAt       string
	SessionEpoch    int64
}
