// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gensqlite

type SecurityEvent struct {
	ID        int64
	UserID    *string
	Kind      string
	Detail    string
	Ip        *string
	UserAgent string
	CreatedAt string
}

type Session struct {
	ID          string
	UserID      string
	FamilyID    string
	PrevID      *string
	RefreshHash []byte
	UserAgent   string
	Ip          *string
	CreatedAt   string
	ExpiresAt   string
	UsedAt      *string
	RevokedAt   *string
}

type TokenFamily struct {
	ID        string
	UserID    string
	CreatedAt string
	RevokedAt *string
}

type User struct {
	ID              string
	Email           string
	PasswordHash    string
	EmailVerifiedAt *string
	CreatedAt       string
	UpdatedAt       string
}
