// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gensqlite

type ConnectedAccount struct {
	ID                string
	UserID            string
	Kind              string
	ProviderAccountID string
	Email             string
	DisplayName       string
	AccessTokenEnc    []byte
	RefreshTokenEnc   []byte
	TokenExpiresAt    *string
	Status            string
	LastError         string
	Ordinal           int64
	AppFolderID       *string
	CreatedAt         string
	UpdatedAt         string
}

type OauthState struct {
	StateHash    []byte
	UserID       string
	Kind         string
	RedirectTo   string
	PkceVerifier *string
	CreatedAt    string
	ExpiresAt    string
}

type SecurityEvent struct {
	ID        int64
	UserID    *string
	Kind      string
	Detail    string
	Ip        *string
	UserAgent string
	CreatedAt string
}

type Session struct {
	ID          string
	UserID      string
	FamilyID    string
	PrevID      *string
	RefreshHash []byte
	UserAgent   string
	Ip          *string
	CreatedAt   string
	ExpiresAt   string
	UsedAt      *string
	RevokedAt   *string
}

type StorageAccount struct {
	ConnectedAccountID string
	TotalBytes         int64
	UsedBytes          int64
	ReservedBytes      int64
	LastSyncedAt       *string
	LastError          string
}

type TokenFamily struct {
	ID        string
	UserID    string
	CreatedAt string
	RevokedAt *string
}

type User struct {
	ID              string
	Email           string
	PasswordHash    string
	EmailVerifiedAt *string
	CreatedAt       string
	UpdatedAt       string
}
