// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gensqlite

import (
	"context"
)

type Querier interface {
	// SQLite dialect of internal/db/queries/sessions.sql. Same contracts, same
	// comments where the reasoning is unchanged; the differences are noted where
	// they exist. now() becomes a bound parameter throughout (see users.sql).
	//
	// KEEP THIS FILE ASCII-ONLY. sqlc v1.31.1's SQLite engine measures a comment's
	// length in bytes and then slices it by rune, so every multi-byte character
	// before a query shifts that query's start by (bytes-1) and truncates its tail.
	// The symptom is a parse error naming a chopped keyword -- one em-dash turns
	// RETURNING into RETURNIN, two into RETURNI, and so on. It is silent until the
	// damage reaches a keyword, so prose written in the house style (which uses
	// em-dashes freely) breaks codegen at a distance. Use "--" for an em-dash and
	// a plain apostrophe for a curly one. The Postgres files are unaffected.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// CreateTokenFamily records a new login's family. Written before the session
	// row, because sessions.family_id has a foreign key to it. Reversing the order
	// gives an FK violation; this order risks at worst an orphan family row, which
	// is harmless.
	//
	CreateTokenFamily(ctx context.Context, arg CreateTokenFamilyParams) error
	// SQLite dialect of internal/db/queries/users.sql.
	//
	// The one systematic difference from the Postgres originals: there is no
	// now(). Every timestamp is a bound parameter supplied by the store, which
	// also makes these queries testable against a fake clock rather than the
	// wall clock. See internal/db/migrations/sqlite/00001_auth.sql.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// DeleteExpiredSessions drops long-dead rows. The Postgres original computes
	// the cutoff in SQL (now() - INTERVAL '30 days'); here the caller passes the
	// already-computed cutoff, so the retention window lives in one place in Go
	// rather than being duplicated in two dialects.
	//
	DeleteExpiredSessions(ctx context.Context, expiresAt string) (int64, error)
	EventsOfKind(ctx context.Context, kind string) ([]SecurityEvent, error)
	ExpireSession(ctx context.Context, arg ExpireSessionParams) (int64, error)
	FamilyRevokedAt(ctx context.Context, id string) (*string, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	// GetSessionByRefreshHash looks a session up by the hash of the presented
	// token. It deliberately returns revoked, used and expired rows too: the
	// caller must be able to tell "already used" from "unknown", because those
	// mean very different things.
	//
	GetSessionByRefreshHash(ctx context.Context, refreshHash []byte) (Session, error)
	// Case-insensitivity comes from the column's NOCASE collation, so this is a
	// plain equality test exactly as the Postgres citext version is.
	//
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error
	// MarkSessionUsed claims a refresh token. The used_at IS NULL predicate makes
	// the claim atomic: two concurrent refreshes with the same token produce one
	// winner and one zero-row result, and the loser is treated as reuse.
	//
	// The NOT EXISTS clause is the authoritative half of the two-part validity
	// condition, and this statement is the only place it is enforced. Known issue
	// #11: a successor inserted after its family was revoked carries revoked_at
	// NULL, so its own column says nothing. Reading the family here, fresh, at
	// claim time, is what makes such a row unusable.
	//
	// The Postgres original carries a long warning that a single statement is
	// atomic but not serialisable, and that under READ COMMITTED an INSERT and a
	// concurrent revocation can each take a snapshot that misses the other. That
	// hazard does not exist here: SQLite serialises writers outright, so any two
	// write statements are ordered with respect to each other. This query is a
	// direct translation and is if anything more strongly protected. The
	// enforcement still belongs on the claim rather than the successor's INSERT --
	// keeping the two dialects behaviourally identical matters more than
	// exploiting the stronger guarantee.
	//
	// Columns are qualified with `sessions.` for a reason beyond style: sqlc's
	// SQLite analyser treats the subquery's table as in scope for the outer
	// statement, so an unqualified `id` is rejected here as ambiguous. Qualifying
	// also keeps this a character-for-character match with the Postgres original
	// apart from the bound timestamps, which is the point -- the two dialects must
	// not drift on the one query that enforces issue #11.
	//
	MarkSessionUsed(ctx context.Context, arg MarkSessionUsedParams) (Session, error)
	RecordSecurityEvent(ctx context.Context, arg RecordSecurityEventParams) error
	// RevokeAllUserSessions signs a user out everywhere.
	//
	// UNSOUND AGAINST A CONCURRENT REFRESH. DO NOT USE YET. Known issue #18.
	//
	// This enumerates the sessions that exist at this instant and cannot bind one
	// inserted afterwards, which is exactly the defect token_families fixed for the
	// family case. Serialised writers do not save this one: the sweep and the
	// successor's INSERT are both well-ordered, and the successor simply lands
	// after the sweep. The fix is the same on both engines -- validity state a
	// racing insert inherits, i.e. a per-user epoch copied from the claimed parent
	// on rotation.
	//
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) (int64, error)
	// RevokeSession revokes a single session.
	//
	// UNSOUND FOR "SIGN OUT THIS DEVICE". DO NOT USE YET. Known issue #18.
	//
	// It revokes one row and cannot bind that session's future successors, so a
	// concurrent refresh rotates the revoked session into a live one. Note also
	// that a session's successors are all in its family by construction, so
	// "revoke this device" and "revoke this family" are the same operation --
	// RevokeTokenFamily plus RevokeSessionFamily is the correct primitive for that
	// job, and this one is the wrong shape regardless of the race.
	//
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
	RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) (int64, error)
	// RevokeTokenFamily kills every token descended from one login, including
	// successors that do not exist yet. This is the enforcing write.
	//
	// Idempotent, and it preserves the first revocation: revoked_at IS NULL means a
	// second call reports zero rows rather than moving the timestamp forward, so
	// the audit trail keeps saying when the family actually died.
	//
	RevokeTokenFamily(ctx context.Context, arg RevokeTokenFamilyParams) (int64, error)
	// --- test support ---------------------------------------------------------
	// These back the inspection helpers the auth test suite uses to assert on
	// state (memstore.go has in-memory equivalents). They are read-only and have
	// no production caller.
	SessionsInFamily(ctx context.Context, familyID string) ([]Session, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
