// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package gensqlite

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, password_hash, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, email, password_hash, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

// SQLite dialect of internal/db/queries/users.sql.
//
// The one systematic difference from the Postgres originals: there is no
// now(). Every timestamp is a bound parameter supplied by the store, which
// also makes these queries testable against a fake clock rather than the
// wall clock. See internal/db/migrations/sqlite/00001_auth.sql.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, email_verified_at, created_at, updated_at FROM users WHERE email = ?
`

// Case-insensitivity comes from the column's NOCASE collation, so this is a
// plain equality test exactly as the Postgres citext version is.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, email_verified_at, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
   SET email_verified_at = ?,
       updated_at        = ?
 WHERE id = ?
   AND email_verified_at IS NULL
`

type MarkEmailVerifiedParams struct {
	EmailVerifiedAt *string
	UpdatedAt       string
	ID              string
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, markEmailVerified, arg.EmailVerifiedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
   SET password_hash = ?,
       updated_at    = ?
 WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}
